name: Update API Password Every 20 Seconds

on:
  workflow_dispatch:  # 允许手动触发
  push:  # 每次 push 代码也可以触发

jobs:
  update-password:
    runs-on: ubuntu-latest
    steps:
      - name: Update API Password every 20 seconds
        run: |
          for i in {1..100}; do  # 循环 100 次，相当于 2000 秒
            echo "Updating password... Attempt $i"
            curl -X POST "https://zpfunapi.zpfun.club/api/update-password" \
            -H "Authorization: Bearer ${{ secrets.UPDATE_SECRET }}"
            echo "Waiting for 20 seconds..."
            sleep 20  # 休眠 20 秒
          done
